wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
area:
  desc: null
  value: false
conv:
  desc: null
  value: 3
embed:
  desc: null
  value: 10
fit:
  desc: null
  value: false
hidden:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.01
max_itr:
  desc: null
  value: 1000
num_walks:
  desc: null
  value: 200
seed:
  desc: null
  value: 10
split_ratio:
  desc: null
  value: 0.7
verbose:
  desc: null
  value: false
walk_len:
  desc: null
  value: 30
